### PR TITLE
Updated regression test setup.

### PR DESCRIPTION
**Pull request by Emoun**
Now all output (stdout and stderr) is output to result.txt.
Instead of using result.txt as the email body, the file is zipped and added as attachment.
This ensures the email is small even though the file is big (MBs).
Now also automatically checks the build for success/faliure and reports in in the email subject.

### CODE REVIEW

**Comment by schoeberl** [comment]
You may log stderr to a file on the server for inspection, but keep just sending stdout as plain text per email.

**Comment by Emoun** [comment]
I have updated the setup. Now the test output that was in the body of the email is there again.
Only the build logs are now in an attached (and zipped) file. We need this because otherwise we wouldn't be able to see what build errors happen. I (and maybe the others too?) don't have access to inspect the build on your user.

I have started a build using this new setup that will send an email to everyone.

**Comment by Emoun** [comment]
@schoeberl Do you any more reservations about merging this PR?

**Comment by schoeberl** [comment]
I don’t think I want that large .zip file in every night email. Could it just stay in Helena if we need to inspect it?

Martin

**Comment by Emoun** [comment]
I can't find a different solution to a compressed build log. The errors we saw a few months ago were incredibly difficult to track down exactly because I couldn't access the build logs on Helena. By having them in the e-mail, we can all access them on demand and can even look in previous emails to compare.
Unless we want to setup some kind of build log hosting service on Helena with access to all Patmos collaborators, I think this is necessary evil.
I can switch to using some other type of compression instead of .zip if you would prefer?

**Comment by schoeberl** [comment]
Feel free to setup the regression test on Helena in a way that everyone can access the .zip files.

Martin

**Comment by Emoun** [comment]
> Everyone can just run the regression test on his own machine to reproduce the log.

This is not always the case, since each machine might be setup differently. E.g. when we had an issue last time, everything ran fine on my machine but failed to build on Helena (because Helena uses an older version of GCC than my machine did). Therefore, we can't assume all failure of the regression test are reproducible on other machines. 

However, maybe #10 can solve this, as everyone can then run the docker image locally to reproduce errors. I'll look into whether that can be a long-term solution that doesn't require build logs to be stored anywhere.

**Comment by Emoun** [comment]
Closing this PR as we are exploring different avenues for regression testing. [E.g. Using Travis](https://github.com/t-crest/patmos-llvm/pull/25)

**Pull request closed without merging**
